package com.example.projectpyramid.domain.services;

import com.example.projectpyramid.data_access.UserMapper;
import com.example.projectpyramid.domain.entities.User;

public class UserServices {

    UserMapper userMapper = new UserMapper();

    public int login(String userName, String password) throws Exception {
        return userMapper.login(userName, password);
    }

    //Services layer method that creates a User object, calls the insert method in the data layer
    //and returns the userId generated by the databas if insertion was successfull.
    public int createUser(String fullName, String userName, String password) throws Exception {
        return userMapper.insert(new User(fullName, userName, password));
    }

    public User getUserFromId(int userId) throws Exception{
       return userMapper.getUser(userId);
    }

    // TODO implement changePassword() method.
    public void changePassword(String oldPassword, String password, String confirmPassword) {

    }
}